### ISSUE TITLE
I have error: Invalid/inactive token. Generate new token using the getToken() method.

### ISSUE THREAD

**Issue by ghost** [krmrn42/Say.Ivona#1]
My token is valid.
I use var ivona = new IvonaRestApi("accessKey", "myemail on ivona", "random proxy");
What am I doing wrong?

**Comment by krmrn42** [comment]
Hi Sava

I think they've completely changed their SDK and API after moving to Amazon hosted services, so I think this project is, unfortunately, not valid anymore. Try requesting their proprietary SDK on their website.

Thanks for giving it a try though :)

Happy coding!
